### ISSUE TITLE
Need FolioReaderKit if possible

### ISSUE THREAD

**Issue by bahadurh** [leminhcse/EpubReader-iOS#18]
Hello i need folioreader kit (your version) where i can do bookmark feature

**Comment by leminhcse** [comment]
Hi Zaman, the latest version of folioreader kit is 1.4.0.
You can check it on github.

Vào Th 4, 23 thg 11, 2022 vào lúc 00:26 BAHADUR ZAMAN <
***@***.***> đã viết:

**Comment by bahadurh** [comment]
but that version doesnt include bookmark feature. and according to your code, i can see the bookmark feature? can you please elaborate?

**Comment by leminhcse** [comment]
Oh, The bookmark feature in my app which I haven't implemented yet.
I just sketched it but haven't started working on it yet because I spent
time handling another feature.

Vào Th 4, 23 thg 11, 2022 vào lúc 00:39 BAHADUR ZAMAN <
***@***.***> đã viết:

**Comment by bahadurh** [comment]
oh okay, i got it. Btw thanks
